version: '3.2'

services:
  auth-service:
    build: auth-service/
    container_name: auth-service
    restart: always
    network_mode: "host"
    hostname: localhost
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/logs
        read_only: false
    ports:
      - 8070:8070
