version: '2'

services:
  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085

  config-server:
    build: config-server/
    container_name: config-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8880:8880

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - config-server
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: localhost
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: localhost
    ports:
    - "27017:27017"

  user-service:
    build: UserService/
    container_name: user-service
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - mongodb
      - rabbitmq
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8100:8100

  medway-webapp:
    build: medway-webapp/
    container_name: medway-webapp
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
    - 8009:8009

  auth-service:
    build: auth-service/
    container_name: auth-service
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
      - rabbitmq
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8070:8070

  medicine-service:
    build: Medicine-Service/
    container_name: medicineService
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
      - rabbitmq
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8105:8105
