version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: localhost
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: localhost
    ports:
    - "27017:27017"