version: '3.2'

services:
  medicine-service:
    build: Medicine-Service/
    container_name: medicineService
    restart: always
    network_mode: "host"
    hostname: localhost
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/logs
        read_only: false
    ports:
      - 8105:8105
