version: '3.2'

services:
  order-service:
    build: order-service/
    container_name: orderService
    restart: always
    network_mode: "host"
    hostname: localhost
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/logs
        read_only: false
    ports:
      - 8110:8110
