version: '3.2'

services:
  prescription-service:
    build: prescription-service/
    container_name: prescriptionService
    restart: always
    network_mode: "host"
    hostname: localhost
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/logs
        read_only: false
    ports:
      - 8071:8071
    
