version: '3.2'

services:
  stripe:
    build: stripe-service/
    container_name: stripeService
    restart: always
    network_mode: "host"
    hostname: localhost
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/logs
        read_only: false
    ports:
      - 8300:8300