version: '2'

services:
  stripe:
    build: SpringBoot-with-stripe/
    container_name: stripeService
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8300:8300