version: '3.2'

services:
  user-service:
    build: UserService/
    container_name: user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/logs
        read_only: false
    ports:
      - 8100:8100